name: my-project
recipe: drupal9
config:
  php: '7.4'
  composer_version: 2.0.7
  via: 'apache:2.4'
  webroot: .
  database: 'mysql:5.7'
  drush: true
  xdebug: true
services:
  appserver:
    build:
      - composer install
tooling:
  drush:
    service: appserver
    env:
      DRUSH_OPTIONS_URI: 'https://my-project.lndo.site'
